---
# file: roles/postgres/tasks/setup_postgress_cluster.yaml
- name: ensures postgres dir exists
  file: 
    path: "/tmp/postgres"
    state: directory
    recurse: true

- name: Copy pg-config.yaml
  ansible.builtin.copy:
    src: ./pg-config.yaml
    dest: /tmp/postgres/pg-config.yaml

- name: Copy pg-operator-manifests.yaml
  ansible.builtin.copy:
    src: ./pg-operator-manifests.yaml
    dest: /tmp/postgres/pg-operator-manifests.yaml

- name: Run kubectl create -f /tmp/postgres/pg-config.yaml
  vars:
    ansible_python_interpreter: /opt/k8s_venv/bin/python
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_temp_path }}"
    state: present
    src: /tmp/postgres/pg-config.yaml

- name: kubectl create -f /tmp/postgres/pg-operator-manifests.yaml
  vars:
    ansible_python_interpreter: /opt/k8s_venv/bin/python
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_temp_path }}"
    state: present
    src: /tmp/postgres/pg-operator-manifests.yaml

