---
- name: Install HAProxy and Keepalived
  apt:
    name:
      - haproxy
      - keepalived
    state: present
    update_cache: yes

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_cfg_path }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart haproxy

- name: Configure Keepalived
  template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_cfg_path }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart keepalived
    
