vip: 192.168.254.120
interface: eth0
control_planes:
  - 192.168.254.201
  - 192.168.254.202
  - 192.168.254.203
haproxy_cfg_path: /etc/haproxy/haproxy.cfg
keepalived_cfg_path: /etc/keepalived/keepalived.conf