---
# file: setup_nodes.yaml
- hosts: ansible_control_node
  vars_files:
    - tf_ansible_vars_file.yaml
  roles:
    - ansible_control_node

- hosts: load_balancers
  become: true
  vars_files:
    - tf_ansible_vars_file.yaml
  roles:
    - loadbalancer

# - hosts: nfs
#   vars_files:
#     - tf_ansible_vars_file.yaml
#   roles:
#     - nfs